apiVersion: batch/v1
kind: CronJob
metadata:
  name: stirimm-wp-rss2db
spec:
  schedule: "*/6 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      activeDeadlineSeconds: 900
      ttlSecondsAfterFinished: 3600
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: stirimm-wp-rss2db
              image: emilburzo/stirimm-wp-rss2db:latest
              imagePullPolicy: Always
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: host
                      optional: false
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: username
                      optional: false
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: password
                      optional: false