apiVersion: batch/v1
kind: CronJob
metadata:
  name: stirimm-wp-rss2db
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: stirimm-wp-rss2db
              image: emilburzo/stirimm-wp-rss2db:latest
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: host
                      optional: false
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: username
                      optional: false
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: stirimm-webapp.db
                      key: password
                      optional: false
          restartPolicy: Never
